data/dataset.yml, tools/common.py
Forcing libyaml bindings ensures consistent YAML output. Also increase
line width to avoid line breaks on file names.
=> tools: force C YAML library

.github/workflows/ci.yml
Add GitHub Actions support with:
* linting for black formatting
* tools/lint.py
* tools/prepare_commit.py
* pytest
=> ci: add GitHub Actions

REPORT.md, data/dataset.yml, data/meta.yml, tools/common.py, tools/gen_meta.py
* Consolidate Mathematica and Wolfram Language into the latter.
* Prevent gen_meta.py from using previous meta.yml when generating from
scratch.
=> tools, data: map Mathematica to Wolfram Language

REPORT.md, data/dataset.yml
=> Tag batch 18

REPORT.md, data/dataset.yml
=> data: label batch 17 samples from #3

REPORT.md, data/dataset.yml
=> data: label batch 16 samples from #3

REPORT.md, data/dataset.yml
Also fixed previous bad tagged file on github.com/igorw/reasoned-php
=> data: label batch 15 samples from #3 

REPORT.md, data/dataset.yml
=> data: label batch 14 samples from #3 

REPORT.md, data/dataset.yml
Samples were identified by selecting those with lowest prediction
confidence using the built-in ExtraTrees classifier.
=> data: add human labels to dubious samples

REPORT.md, data/dataset.yml, tools/vote.py
Weight each (auto)annotator with its precision.
=> Add weighted voting

REPORT.md, data/dataset.yml
Misclassifications detected when comparing with pygments mappings.
=> data: manual annotations batch

Pipfile, Pipfile.lock, REPORT.md, data/dataset.yml, data/meta.yml, tools/classify_pygments.py, tools/gen_meta.py
=> Add Pygments mapping and annotations

Pipfile, Pipfile.lock
=> Update Pipfile, remove old conf

Pipfile.lock
=> Update deps: pandas, pytest, flake8

data/meta.yml, tools/gen_meta.py
=> Update to linguist 7.12.2

REPORT.md, data/dataset.yml, tools/linguist_wrapper.rb, tools/vote.py
Most were not being updated correctly.
=> Fix and update linguist annotations

poetry.lock, pyproject.toml, tools/harvest.py, tools/test_harvest.py
* Parallelize per repository, not per language.
* Use code search API (v3) instead of GraphQL, this enables more fine
grained search.
* Add parameters to harvest a single language and add extra query
parameters.
=> Improve harvest process

REPORT.md, data/dataset.yml
Based on classification errors
=> Manual annotation batch

data/meta.yml, tools/common.py, tools/gen_meta.py
These are based on github/linguist's groups. Groups provide distinction
useful for coarse and fine grained classification.
=> Add groups

poetry.lock, pyproject.toml
=> Update deps and remove ipython
